### PR TITLE
Add percentile fold to hxMath 

### PR DESCRIPTION
**Pull request by jamesdgessel**
Added percentile folding func for use in axon folds. 

Examples 

```
[0,25,50,75,100].fold( percentile(75)    ) => 75
[0,25,50,75,100].fold( percentile(75%)   ) => 75
[0,25,50,75,100].fold( percentile(0.75)  ) => 75
[0,25,50,75,100].fold( percentile(1)     ) => 1 // treated as 1%, not 100%
```

MathFuncs.fan 
- **percentileCalc**   *(nodoc)*
- **percentile**          *(shortcut to percentileCalc with single % input)*

NumberFold.fan
- **percentile**           (main calcs) 

MathTest.fan
- added testing for scenarious above

### CODE REVIEW

**Comment by briansfrank** [comment]
This seems like a better design.  Notes:

1. the header's changelog if for significant changes, not something like this just adding a function
2. Your boundary checks are in two different places and the 0/1 and 0/100 is kind of confusing too; I'd say we pick one; probably just 0.0 to 1.0 since that is the direction I'm going with Ion for alpha transparency, etc
3. Don't wrap the single lines with curly braces {throw Err(xxx")} should just be throw ArgErr
4. There are changes to the existing test which should not be included in the diff (86-96); just create brand new test method and lets not change what is already there

But overall I find this function ambiguous.  It doesn't really specify the precise semantics of that percentile means or how it works.  And the examples don't really help explain it.  I really don't understand in your example why the last example returns 1 (I guess because of some interpolation, but not clear because your samples are all perfectly aligned with 100). 

So need to beef up docs and I'd like to see how this compares to existing percentile functions in other packages like numpy, mathmatica, etc.  I'd say write the spec first as a comment in the PR and link to other implementations

**Comment by jamesdgessel** [comment]
1. What do you mean!? This is hugely significant, its my first contribution!! ....... Removed :)
2. Numpy's np.quantile supports 0-1 while np.percentile supports 0-100 (methods are [equivalent](https://github.com/numpy/numpy/blob/7c0e2e4224c6feb04a2ac4aa851f49a2c2f6189f/numpy/lib/_function_base_impl.py#L4171)), Mathematica's quantile supports 0-1. I like the flexibility of having both, but if you prefer to go with 0-1 I'm ok with that. I personally think 0-100 is more intuitive. 
3. Understood - will update
4. Will fix that - I originally added my tests to the old test as columns, but later decided to move it to its own section. The only difference is whitespace, I'll fix it so it doesn't show as a delta. 

Sounds like I need to beef up my docs game! I'll put better examples in to illustrate more behaviour. My method is equivalent to the "linear" interpolation method from numpy and mathematica, though I'd like to add more options. I'll add my proposed specs to my next comment. 

### Numpy docs 

- [Percentile](https://github.com/numpy/numpy/blob/7c0e2e4224c6feb04a2ac4aa851f49a2c2f6189f/numpy/lib/_function_base_impl.py#L4068) supports inputs 0-100 
- [Quantile](https://github.com/numpy/numpy/blob/7c0e2e4224c6feb04a2ac4aa851f49a2c2f6189f/numpy/lib/_function_base_impl.py#L4284) supports inputs 0-1
- Both support all [methods](https://github.com/numpy/numpy/blob/7c0e2e4224c6feb04a2ac4aa851f49a2c2f6189f/numpy/lib/_function_base_impl.py#L4121)  above, and more

### Mathematica docs
 - [Quantile](https://reference.wolfram.com/language/ref/Quantile.html.en) takes fractional inputs (0-1)
 - And supports similar but more flexible [methods](https://reference.wolfram.com/language/ref/Quantile.html.en#:~:text=of%20range.%20%C2%BB-,Common,-choices%20of%20parameters)

**Comment by jamesdgessel** [comment]
### Hx Percentile (my proposed spec) 
Computes the p*th* percentile of a list of numbers according to the specified interpolation method. 

Usage: `list.percentile(p, "method")`

Supported Methods
- **Linear** (default): Interpolates proportionally between two closest values.
- **Nearest**: Rounds to the nearest data point.
- **Lower**: Uses the closest value at or below the percentile.
- **Higher**: Uses the closest value at or above the percentile.
- **Midpoint**: Averages the two nearest points.

Logic 
```
p: percentile (decimal 0-1)
n: list size
rank: p * (n-1) // this is the index of the percentile in your list
// if rank is an integer, return list[rank]
// if rank is not an integer, interpolate via one of the above methods (illustrated below in examples)
```

Examples 
```
[1,2,3,4,5].percentile(0.5) => 3 // rank=2 is an int so we can index[2] directly

[10,10,10, 25, 100].percentile(0.7, method)
    rank = (0.7 * 4) => 2.8 

    //adjust rank based on method
    nearest =  index[3]                // => 25
    lower =    index[2]                // => 10
    higher =   index[3]                // => 25

    //or interpolate for these methods

    //takes the 2 closest indices and calculates midpoint
    midpoint = (25-10)/2 + 10          // => 17.5

    //takes the 2 closest indices and calculates weighted average
    linear =   (0.2 * 10) + (0.8 * 25) // => 22
```

**Comment by jamesdgessel** [comment]
Let me know what you think and I'll proceed with any changes :D

**Comment by briansfrank** [comment]
Those docs are much more clear and the design seems more polished.

Lets only support 0.0 to 1.0.  That is a convention I have already started:

https://skyfoundry.com/doc/lib-ui/func~vizInterpolateRgb

Based on both mathematica and polars calling that function quantile, then our implementation should use that term too.

https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.quantile.html

I like the option for picking how interpolation is done and looks like most implementations support it.  However, feel like it should be an opts Dict.  But maybe just a string is fine for now and if we need to extend it, we can change that as convenience for {method:"nearest"}. That part I'm still not sure about.

**Comment by jamesdgessel** [comment]
@briansfrank updates complete and tests passed. 

1. Fix comments &  conventions
2. Changed name to "quantile" 
3. Added "method" as a second input that defaults to "linear". It is a string for now, if you decide you want a dict let me know and I can update. 
4. Beefed up docs - I wasn't sure if you wanted all the details in the fandoc, but I put it all there
5. Fixed tests and added checks for methods & errors (to get the test results I wrote a brief python script that runs the same inputs through numpy.quantile. I couldn't think of a good way to include that code short of pasting it as a comment, but lmk if you want to see it.)

**Comment by briansfrank** [comment]
That is pretty close to ready.  Still a few things:

- lets nuke old code in there commented out such as this line:

```
//if (perc == null) throw ArgErr("Quantile must be a number, not null")
```

- also I don't think we need the todo comments in NumberFold
- we don't need double checks for the method name, you can remove this check and just rely on the check on the switch statement:

```
["linear","nearest","higher","lower","midpoint"].contains(method)) throw ArgErr("Invalid method")

- it would be a little cleaner to actually make that a switch

```
switch (method)
 case "lower":    return array[k].toFloat 
  case "higher":   return array[k+1]
  case "nearest": return array[i.round.toInt]
  ...
```

- do be clear in docs, I think you list the method names in lowercase since that is how they are used in the API
```

- also make sure you code is using two spaces for indent and your editor is setup to strip trailing whitespace

**Comment by jamesdgessel** [comment]
@briansfrank addressed :D

**Pull request merged**
